update_entities:
  name: Update all entities
  description: >
    Carrying out loading of the entities.
  fields:
    forced:
      # description: Se forzare il caricamento di tutte le informazioni, come le info delle stanze
      name: Force loading
      description: Whether to force loading of all information, such as room info
      example: True

exec_vimar_sql:
  name: Execute Vimar SQL
  description: >
    Execute a SQL query on the Vimar web server.
  fields:
    sql:
      name: SQL Query
      description: SQL Query to be run on the webserver.
      example: SELECT 1

reload_default:
  name: Remove and reload
  description: >
    Removing all entites and then reload - reseting everything to default names.

reload:
  name: Reload
  description: Reload Vimar integration.
